var itens = [
    {
        "id": "acordeon",
        "nome": "ACORDEON",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Acordeon.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Acordeon.mp3",
    },
    {
        "id": "afoxe",
        "nome": "AFOXÉ",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Afoxé.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Afoxe.mp3",
    },
    {
        "id": "agogo",
        "nome": "AGOGÔ",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Agogo.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Agogo.mp3",
    },
    { 
        "id": "bateria",
        "nome": "BATERIA",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Bateria.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Bateria.mp3",
    },
    {
        "id": "caixa",
        "nome": "CAIXA",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Caixa.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Caixa.mp3",
    },
    {
        "id": "carrilhao",
        "nome": "CARRILHÃO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Carrilhão.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Carrilhao.mp3",
    },
    {
        "id": "cavaquinho",
        "nome": "CAVAQUINHO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Cavaquinho.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Cavaquinho.mp3",
    },
    {
        "id": "flauta",
        "nome": "FLAUTA",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/flautaDoce.jpeg",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Flauta.mp3",
    },
    {
        "id": "gaita",
        "nome": "GAITA",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Gaita.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Gaita.mp3",
    },
    {
        "id": "gongo",
        "nome": "GONGO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Gongo.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Gongo.mp3",
    },
    {
        "id": "guitarra",
        "nome": "GUITARRA",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Guitarra.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Guitarra.mp3",
    },
    {
        "id": "pandeiro",
        "nome": "PANDEIRO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Pandeiro.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Pandeiro.mp3",
    },
    {
        "id": "piano",
        "nome": "PIANO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Piano.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Piano.mp3",
    }, 
    {
        "id": "pratos",
        "nome": "PRATOS",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Pratos.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Pratos.mp3",
    },
    {
        "id": "saxofone",
        "nome": "SAXOFONE",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Saxofone.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Saxofone.mp3",
    }, 
    {
        "id": "tamborim",
        "nome": "TAMBORIM",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Tamborim.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Tamborim.mp3",
    }, 
    {
        "id": "triangulo",
        "nome": "TRIÂNGULO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Triângulo.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Triangulo.mp3",
    },
    {
        "id": "trombone",
        "nome": "TROMBONE",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Trombone.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Trombone.mp3",
    },
    {
        "id": "tuba",
        "nome": "TUBA",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Tuba.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Tuba.mp3",
    },
    {
        "id": "violino",
        "nome": "VIOLINO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Violino.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Violino.mp3",
    },
    {
        "id": "violino",
        "nome": "VIOLINO",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Violão.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Violino.mp3",
    },
    {
        "id": "xilofone",
        "nome": "XILOFONE",
        "imagem": "../../../Assets/Image/InstrumentosMusicaisFotos/Xilofone.PNG",
        "audio": "../../../Assets/Audio/Instrumentos Sons/Xilofone.mp3",
    } 
]
